version = 0.1

[default]
  [default.global]
    [default.global.parameters]
      stack_name = "vouchmark"
      region = "ap-south-1"

  [default.build]
    [default.build.parameters]
      cached = true
      parallel = true

  [default.deploy]
    [default.deploy.parameters]
      capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
      confirm_changeset = false
      fail_on_empty_changeset = false
      resolve_s3 = true
      parameter_overrides = "BedrockModelId=anthropic.claude-sonnet-4-20250514-v1:0 DemoMode=false AllowedOrigin=* GuardrailId= GuardrailVersion= UseCloudFront=false"