from __future__ import annotations

from src.demo import demo_analysis
from src.models import AnalysisContext


def test_demo_returns_structured_payload():
    out = demo_analysis()
    assert out["ok"] is True
    a = out["analysis"]
    assert a["generatedVia"] == "demo"
    assert len(a["assessments"]) == 3
    assert a["verdict"]["label"] == "LIKELY_INVALID"
    assert "Grievance Officer" in a["letter"]
    assert "This draft was generated by Vouchmark" in a["letter"]
    assert a["disclaimer"]


def test_demo_verdict_updates_with_preexisting_context():
    base = demo_analysis(language="English")
    # Same fixture, but with a history of the disease BEFORE the policy
    # -> the pre-existing ground flips to strong, moving the verdict.
    with_ctx = demo_analysis(
        context=AnalysisContext(policy_years=3, diagnosis_age_years=6)
    )
    by_cat = {ass["category"]: ass["grounds_strength"] for ass in with_ctx["analysis"]["assessments"]}
    assert by_cat["pre_existing"] == "strong"
    labels = {x["analysis"]["verdict"]["label"] for x in (base, with_ctx)}
    assert "LIKELY_INVALID" in labels


def test_demo_letter_is_copyable_and_escaped():
    out = demo_analysis()
    letter = out["analysis"]["letter"]
    assert letter.strip()
    assert "\x00" not in letter  # no binary junk for the browser to choke on