from __future__ import annotations

import pytest

from src.demo import demo_analysis
from src.models import AnalysisContext

LANGUAGES = ["English", "Hinglish", "Hindi", "Tamil", "Telugu", "Bengali"]


@pytest.mark.parametrize("language", LANGUAGES)
def test_counter_letter_builds_in_every_supported_language(language):
    out = demo_analysis(language=language)
    letter = out["analysis"]["letter"]
    assert "Grievance Officer" in letter
    assert "CLM20260828-00741" in letter
    assert "This draft was generated by Vouchmark" in letter
    assert "\x00" not in letter


def test_letter_echoes_extracted_policy_and_claim_numbers():
    letter = demo_analysis()["analysis"]["letter"]
    assert "EHAI/FLA/21/ID-0012354" in letter
    assert "CLM20260828-00741" in letter


def test_summary_markdown_tags_each_strength():
    out = demo_analysis()
    md = out["analysis"]["markdownSummary"]
    assert "Likely contestable" in md
    for a in out["analysis"]["assessments"]:
        assert a["label"] in md


def test_letter_includes_amount_references_when_given():
    out = demo_analysis(
        context=AnalysisContext(amount_claimed=682000, amount_rejected=682000)
    )
    letter = out["analysis"]["letter"]
    assert "682,000" in letter


def test_letter_uses_placeholders_when_amounts_missing():
    letter = demo_analysis()["analysis"]["letter"]
    assert "[amount in INR]" in letter


def test_metadata_from_letter_appears_in_draft():
    out = demo_analysis()
    letter = out["analysis"]["letter"]
    assert "Policy started: 2021-04-14" in letter
    assert "Sum insured: Rs. 500,000" in letter
    assert "Rejection letter dated: 2026-09-02" in letter


def test_extraction_metadata_is_public():
    ex = demo_analysis()["analysis"]["extraction"]
    assert ex["policy_holder_name"] == "[policy holder name]"
    assert ex["policy_start_date"] == "2021-04-14"
    assert ex["sum_insured"] == 500000.0