"""Case persistence — DynamoDB, lazily connected.

Schema (table: `vouchmark-cases`):
  PK  deviceId      (anonymous device hash from the frontend)
  SK  caseId        (uuid generated by the API)
  GSI1PK  verdictLabel  (stats/digest queries later if needed — unused today)

We deliberately keep *no* free-text PII beyond what the user chose to send:
the extracted text is stored truncated, and results are stored in full (they
are the whole point of the app). TTL is optional to keep the table from
growing forever in a demo.
"""
from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from typing import Any, Optional

_TABLE = os.environ.get("CASES_TABLE", "vouchmark-cases")

MAX_LIST_LIMIT = 50

# In-memory fallback so the app stays fully functional WITHOUT AWS (offline
# demo, laptop demos, Build-It track, smoke tests): persisted per-process.
_memory: dict[tuple[str, str], dict] = {}


def _ddb(use_dynamodb_local: bool = False):
    import boto3  # lazy
    if use_dynamodb_local or os.environ.get("DYNAMODB_LOCAL"):
        return boto3.resource(
            "dynamodb",
            endpoint_url=os.environ.get("DYNAMODB_LOCAL_ENDPOINT", "http://localhost:8000"),
            region_name="us-east-1",
            aws_access_key_id="local",
            aws_secret_access_key="local",
        )
    return boto3.resource("dynamodb")


def _build_item(device_id: str, case_id: str, payload: dict) -> dict:
    item: dict[str, Any] = {
        "deviceId": device_id,
        "caseId": case_id,
        "createdAt": datetime.now(timezone.utc).isoformat(),
        "verdictLabel": payload["analysis"]["verdict"]["label"],
        "fightScore": payload["analysis"]["verdict"]["fight_score"],
        "language": payload["analysis"]["language"],
        "generatedVia": payload["analysis"]["generatedVia"],
        "digest": json.dumps(
            {
                "insurer": payload["analysis"]["extraction"].get("insurer"),
                "diagnosis": payload["analysis"]["extraction"].get("diagnosis"),
                "amountRejected": payload["analysis"]["extraction"].get("amount_rejected"),
                "reasons": [a["category"] for a in payload["analysis"]["assessments"]],
                "headline": payload["analysis"]["verdict"]["headline"],
            },
            ensure_ascii=False,
            default=str,
        ),
        "analysis": json.dumps(payload["analysis"], ensure_ascii=False, default=str),
    }
    if os.environ.get("CASES_TTL_DAYS"):
        try:
            item["expiresAt"] = int(
                datetime.utcnow().timestamp() + int(os.environ["CASES_TTL_DAYS"]) * 86400
            )
        except ValueError:
            pass
    return item


def save_case(device_id: str, case_id: str, payload: dict) -> None:
    """Best-effort write. Persistence failures must never fail the request."""
    if not device_id or not case_id:
        return
    item = _build_item(device_id, case_id, payload)
    key = (device_id, case_id)
    try:
        _ddb().Table(_TABLE).put_item(Item=item)
    except Exception:  # noqa: BLE001 — offline laptop / no creds: fall back to memory
        _memory[key] = item


def _memory_list(device_id: str, limit: int, cursor: Optional[str]) -> tuple[list[dict], Optional[str]]:
    entries = [
        (k, v) for k, v in _memory.items() if k[0] == device_id
    ]
    entries.sort(key=lambda kv: kv[1].get("createdAt", ""), reverse=True)
    if cursor:
        start = next(
            (i for i, (k, _v) in enumerate(entries) if k[1] == cursor), None
        )
        if start is not None:
            entries = entries[start + 1:]
        else:
            entries = []
    page = entries[:limit]
    next_cursor = page[-1][0][1] if len(page) == limit else None
    return [_public_digest_item(v) for _k, v in page], next_cursor


def list_cases(
    device_id: str, limit: int = 10, cursor: Optional[str] = None
) -> tuple[list[dict], Optional[str]]:
    """Newest-first cases for a device. Returns (items, nextCursor)."""
    if not device_id:
        return [], None
    bounded = max(1, min(int(limit), MAX_LIST_LIMIT))
    try:
        table = _ddb().Table(_TABLE)
        kwargs: dict[str, Any] = {
            "KeyConditionExpression": "deviceId = :d",
            "ExpressionAttributeValues": {":d": device_id},
            "ScanIndexForward": False,
            "Limit": bounded,
        }
        if cursor:
            kwargs["ExclusiveStartKey"] = {
                "deviceId": device_id,
                "caseId": cursor,
            }
        resp = table.query(**kwargs)
    except Exception:  # noqa: BLE001 — no DynamoDB: serve from the memory store
        return _memory_list(device_id, bounded, cursor)
    out: list[dict] = []
    for it in resp.get("Items", []):
        out.append(_public_digest_item(it))
    last = resp.get("LastEvaluatedKey") or {}
    next_cursor = last.get("caseId") or None
    return out, next_cursor


def get_case(device_id: str, case_id: str) -> Optional[dict]:
    """Full record for one case, including the stored analysis, or None."""
    if not device_id or not case_id:
        return None
    try:
        table = _ddb().Table(_TABLE)
        resp = table.get_item(
            Key={"deviceId": device_id, "caseId": case_id},
            ConsistentRead=False,
        )
    except Exception:  # noqa: BLE001 — no DynamoDB: serve from the memory store
        item = _memory.get((device_id, case_id))
        return _public_case(item) if item else None
    item = resp.get("Item")
    return _public_case(item) if item else None


def _public_digest_item(item: dict) -> dict:
    try:
        digest = json.loads(item.get("digest") or "{}")
    except json.JSONDecodeError:
        digest = {}
    return {
        "caseId": item.get("caseId"),
        "createdAt": item.get("createdAt"),
        "verdictLabel": item.get("verdictLabel"),
        "fightScore": item.get("fightScore"),
        "language": item.get("language"),
        "digest": digest,
    }


def _public_case(item: dict) -> dict:
    try:
        analysis = json.loads(item.get("analysis") or "{}")
    except json.JSONDecodeError:
        analysis = {}
    return {
        "caseId": item.get("caseId"),
        "createdAt": item.get("createdAt"),
        "verdictLabel": item.get("verdictLabel"),
        "fightScore": item.get("fightScore"),
        "language": item.get("language"),
        "analysis": analysis,
        "digest": json.loads(item.get("digest") or "{}"),
    }