"""Case persistence — DynamoDB, lazily connected.

Schema (table: `vouchmark-cases`):
  PK  deviceId      (anonymous device hash from the frontend)
  SK  caseId        (uuid generated by the API)
  GSI1PK  verdictLabel  (stats/digest queries later if needed — unused today)

We deliberately keep *no* free-text PII beyond what the user chose to send:
the extracted text is stored truncated, and results are stored in full (they
are the whole point of the app). TTL is optional to keep the table from
growing forever in a demo.
"""
from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from typing import Any

_TABLE = os.environ.get("CASES_TABLE", "vouchmark-cases")


def _ddb(use_dynamodb_local: bool = False):
    import boto3  # lazy
    if use_dynamodb_local or os.environ.get("DYNAMODB_LOCAL"):
        return boto3.resource(
            "dynamodb",
            endpoint_url=os.environ.get("DYNAMODB_LOCAL_ENDPOINT", "http://localhost:8000"),
            region_name="us-east-1",
            aws_access_key_id="local",
            aws_secret_access_key="local",
        )
    return boto3.resource("dynamodb")


def save_case(device_id: str, case_id: str, payload: dict) -> None:
    """Best-effort write. Persistence failures must never fail the request."""
    if not device_id or not case_id:
        return
    try:
        table = _ddb().Table(_TABLE)
    except Exception:  # noqa: BLE001 — offline laptop, no creds, nothing to save to
        return
    item: dict[str, Any] = {
        "deviceId": device_id,
        "caseId": case_id,
        "createdAt": datetime.now(timezone.utc).isoformat(),
        "verdictLabel": payload["analysis"]["verdict"]["label"],
        "fightScore": payload["analysis"]["verdict"]["fight_score"],
        "language": payload["analysis"]["language"],
        "generatedVia": payload["analysis"]["generatedVia"],
        "digest": json.dumps(
            {
                "insurer": payload["analysis"]["extraction"].get("insurer"),
                "diagnosis": payload["analysis"]["extraction"].get("diagnosis"),
                "amountRejected": payload["analysis"]["extraction"].get("amount_rejected"),
                "reasons": [a["category"] for a in payload["analysis"]["assessments"]],
                "headline": payload["analysis"]["verdict"]["headline"],
            },
            ensure_ascii=False,
            default=str,
        ),
    }
    if os.environ.get("CASES_TTL_DAYS"):
        try:
            item["expiresAt"] = int(
                datetime.utcnow().timestamp() + int(os.environ["CASES_TTL_DAYS"]) * 86400
            )
        except ValueError:
            pass
    try:
        table.put_item(Item=item)
    except Exception:  # noqa: BLE001 — never break the user flow for storage
        pass


def list_cases(device_id: str, limit: int = 10) -> list[dict]:
    if not device_id:
        return []
    try:
        table = _ddb().Table(_TABLE)
    except Exception:  # noqa: BLE001
        return []
    try:
        resp = table.query(
            KeyConditionExpression="deviceId = :d",
            ExpressionAttributeValues={":d": device_id},
            ScanIndexForward=False,  # newest first
            Limit=max(1, min(int(limit), 50)),
        )
    except Exception:  # noqa: BLE001
        return []
    out: list[dict] = []
    for it in resp.get("Items", []):
        try:
            out.append({
                "caseId": it["caseId"],
                "createdAt": it.get("createdAt"),
                "verdictLabel": it.get("verdictLabel"),
                "fightScore": it.get("fightScore"),
                "language": it.get("language"),
                "digest": json.loads(it.get("digest") or "{}"),
            })
        except json.JSONDecodeError:
            continue
    return out