"""Case persistence — DynamoDB, lazily connected.

Schema (table: `vouchmark-cases`):
  PK  deviceId      (anonymous device hash from the frontend)
  SK  caseId        (uuid generated by the API)
  GSI1PK  verdictLabel  (stats/digest queries later if needed — unused today)

We deliberately keep *no* free-text PII beyond what the user chose to send:
the extracted text is stored truncated, and results are stored in full (they
are the whole point of the app). TTL is optional to keep the table from
growing forever in a demo.
"""
from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from typing import Any, Optional

_TABLE = os.environ.get("CASES_TABLE", "vouchmark-cases")

MAX_LIST_LIMIT = 50


def _ddb(use_dynamodb_local: bool = False):
    import boto3  # lazy
    if use_dynamodb_local or os.environ.get("DYNAMODB_LOCAL"):
        return boto3.resource(
            "dynamodb",
            endpoint_url=os.environ.get("DYNAMODB_LOCAL_ENDPOINT", "http://localhost:8000"),
            region_name="us-east-1",
            aws_access_key_id="local",
            aws_secret_access_key="local",
        )
    return boto3.resource("dynamodb")


def save_case(device_id: str, case_id: str, payload: dict) -> None:
    """Best-effort write. Persistence failures must never fail the request."""
    if not device_id or not case_id:
        return
    try:
        table = _ddb().Table(_TABLE)
    except Exception:  # noqa: BLE001 — offline laptop, no creds, nothing to save to
        return
    item: dict[str, Any] = {
        "deviceId": device_id,
        "caseId": case_id,
        "createdAt": datetime.now(timezone.utc).isoformat(),
        "verdictLabel": payload["analysis"]["verdict"]["label"],
        "fightScore": payload["analysis"]["verdict"]["fight_score"],
        "language": payload["analysis"]["language"],
        "generatedVia": payload["analysis"]["generatedVia"],
        "digest": json.dumps(
            {
                "insurer": payload["analysis"]["extraction"].get("insurer"),
                "diagnosis": payload["analysis"]["extraction"].get("diagnosis"),
                "amountRejected": payload["analysis"]["extraction"].get("amount_rejected"),
                "reasons": [a["category"] for a in payload["analysis"]["assessments"]],
                "headline": payload["analysis"]["verdict"]["headline"],
            },
            ensure_ascii=False,
            default=str,
        ),
        "analysis": json.dumps(payload["analysis"], ensure_ascii=False, default=str),
    }
    if os.environ.get("CASES_TTL_DAYS"):
        try:
            item["expiresAt"] = int(
                datetime.utcnow().timestamp() + int(os.environ["CASES_TTL_DAYS"]) * 86400
            )
        except ValueError:
            pass
    try:
        table.put_item(Item=item)
    except Exception:  # noqa: BLE001 — never break the user flow for storage
        pass


def list_cases(
    device_id: str, limit: int = 10, cursor: Optional[str] = None
) -> tuple[list[dict], Optional[str]]:
    """Newest-first cases for a device. Returns (items, nextCursor)."""
    if not device_id:
        return [], None
    try:
        table = _ddb().Table(_TABLE)
    except Exception:  # noqa: BLE001
        return [], None
    try:
        kwargs: dict[str, Any] = {
            "KeyConditionExpression": "deviceId = :d",
            "ExpressionAttributeValues": {":d": device_id},
            "ScanIndexForward": False,
            "Limit": max(1, min(int(limit), MAX_LIST_LIMIT)),
        }
        if cursor:
            kwargs["ExclusiveStartKey"] = {
                "deviceId": device_id,
                "caseId": cursor,
            }
        resp = table.query(**kwargs)
    except Exception:  # noqa: BLE001
        return [], None
    out: list[dict] = []
    for it in resp.get("Items", []):
        try:
            out.append({
                "caseId": it["caseId"],
                "createdAt": it.get("createdAt"),
                "verdictLabel": it.get("verdictLabel"),
                "fightScore": it.get("fightScore"),
                "language": it.get("language"),
                "digest": json.loads(it.get("digest") or "{}"),
            })
        except json.JSONDecodeError:
            continue
    last = resp.get("LastEvaluatedKey") or {}
    next_cursor = last.get("caseId") or None
    return out, next_cursor


def get_case(device_id: str, case_id: str) -> Optional[dict]:
    """Full record for one case, including the stored analysis, or None."""
    if not device_id or not case_id:
        return None
    try:
        table = _ddb().Table(_TABLE)
    except Exception:  # noqa: BLE001
        return None
    try:
        resp = table.get_item(
            Key={"deviceId": device_id, "caseId": case_id},
            ConsistentRead=False,
        )
    except Exception:  # noqa: BLE001
        return None
    item = resp.get("Item")
    if not item:
        return None
    try:
        analysis = json.loads(item.get("analysis") or "{}")
    except json.JSONDecodeError:
        analysis = {}
    return {
        "caseId": item.get("caseId"),
        "createdAt": item.get("createdAt"),
        "verdictLabel": item.get("verdictLabel"),
        "fightScore": item.get("fightScore"),
        "language": item.get("language"),
        "analysis": analysis,
        "digest": json.loads(item.get("digest") or "{}"),
    }