"""Deterministic counter-letter builder.

Used as the *fallback* when Bedrock is unavailable (demo mode, offline
Build-It demos, model timeouts) and as the structural skeleton that the
LLM then enriches in production mode. Produces a plain, reviewable letter —
never a promise of an outcome.
"""
from __future__ import annotations

from datetime import date

from .models import AnalysisContext


def _fmt(v: float | None) -> str:
    if v is None:
        return "[amount in INR]"
    return f"Rs. {v:,.0f}"


def build_counter_letter(
    extraction: dict,
    assessments: list[dict],
    ctx: AnalysisContext,
) -> str:
    """Build a draft counter letter from extraction + assessments."""
    insurer = extraction.get("insurer") or "[insurer name]"
    policy = extraction.get("policy_number") or "[policy number]"
    claim = extraction.get("claim_number") or "[claim number]"
    patient = extraction.get("patient_name") or "[insured name]"
    holder = extraction.get("policy_holder_name") or patient or "[policy holder name]"
    diagnosis = extraction.get("diagnosis") or "the treatment"
    hospital = extraction.get("hospital") or "[hospital name]"
    policy_start = extraction.get("policy_start_date") or "[policy start date]"
    sum_insured = extraction.get("sum_insured") or None
    rejection_date = extraction.get("rejection_date") or "[date of the letter]"

    weak = [a for a in assessments if a["grounds_strength"] == "weak"]
    undetermined = [a for a in assessments if a["grounds_strength"] == "undetermined"]
    contestable = weak + undetermined

    lines: list[str] = []
    for i, a in enumerate(contestable, 1):
        lines.append(f"{i}) {a['label']}. {a['why']}")
    for i, a in enumerate(contestable, 1):
        lines.append(
            f"{i}) Evidence attached against '{a['label']}': "
            + "; ".join(f"• {e}" for e in a["evidence"])
        )

    lines_text = "\n\n".join(lines)

    return f"""\
DRAFT — {date.today().strftime('%d %b %Y')}
(Review carefully before sending. Informational draft, not legal advice.)

To:
The Grievance Officer / Claims Department
{insurer}

Re: Request for reconsideration — {diagnosis}
Policy No: {policy} | Claim No: {claim}
Patient / Insured: {patient}
Policy holder: {holder}
Rejection letter dated: {rejection_date}

Dear Sir/Madam,

This letter relates to the claim of {patient} for treatment at {hospital}
({diagnosis}) and the rejection communicated for policy {policy}, claim {claim}.

I believe the grounds stated in the rejection do not match the terms of my
policy, for the following reasons:

{lines_text}

I am attaching supporting documents as listed above and request that the
claim be re-examined under your internal grievance process. Please confirm
receipt of this letter and provide a written decision within 30 days of
receipt.

If I do not receive a response in that time, my next step will be to raise
this under IRDAI's grievance mechanism (Bima Bharosa) and the consumer
ombudsman service.

Facts from the letter:
- Policy started: {policy_start}
- Sum insured: {_fmt(sum_insured)}
- Claimed amount: {_fmt(ctx.amount_claimed)}
- Rejected amount: {_fmt(ctx.amount_rejected)}

Yours faithfully,
[{patient} / [claimant signature]]

---
This draft was generated by Vouchmark as informational support.
It is NOT legal or financial advice, and it does not guarantee any outcome.
"""


def short_summary_markdown(
    extrac: dict, assessments: list[dict], verdict: dict
) -> str:
    heads = {
        "LIKELY_INVALID": "🔴 Likely contestable",
        "LIKELY_VALID": "🟡 Looks valid on paper",
        "NEEDS_INPUT": "🟠 Needs documents first",
    }
    h = heads.get(verdict.get("label"), heads["NEEDS_INPUT"])
    parts = [f"**{h}** — {verdict.get('headline', '')}", ""]
    for a in assessments:
        mark = {"weak": "❌", "strong": "✅", "undetermined": "❓"}[a["grounds_strength"]]
        parts.append(f"- {mark} **{a['label']}** — {a['why']}")
    return "\n".join(parts)